# Generated by Django 5.1.6 on 2025-03-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_deposit_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='proof_of_payment',
        ),
        migrations.AddField(
            model_name='deposit',
            name='crypto_currency',
            field=models.CharField(blank=True, choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('LTC', 'Litecoin')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30),
        ),
    ]
